<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="14428" started-at="2021-08-12T14:21:39Z" finished-at="2021-08-12T14:21:54Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="14428" started-at="2021-08-12T14:21:39Z" finished-at="2021-08-12T14:21:54Z">
      <class name="org.cts.test.prog.Facebook_Login_Data">
        <test-method status="PASS" signature="beforeclass()[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="beforeclass" is-config="true" duration-ms="9483" started-at="2021-08-12T14:21:39Z" finished-at="2021-08-12T14:21:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeclass -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="beforemethod" is-config="true" duration-ms="16" started-at="2021-08-12T14:21:49Z" finished-at="2021-08-12T14:21:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="PASS" signature="Test2()[pri:-1, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="Test2" duration-ms="0" started-at="2021-08-12T14:21:49Z" finished-at="2021-08-12T14:21:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="aftermethod" is-config="true" duration-ms="0" started-at="2021-08-12T14:21:49Z" finished-at="2021-08-12T14:21:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="beforemethod" is-config="true" duration-ms="0" started-at="2021-08-12T14:21:49Z" finished-at="2021-08-12T14:21:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="FAIL" signature="test(java.lang.String, java.lang.String)[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="test" duration-ms="1491" started-at="2021-08-12T14:21:49Z" data-provider="login" finished-at="2021-08-12T14:21:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mano]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[45678]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Verify the Username expected [] but found [ThiyagarajaN],
verify the password expected [] but found [9876543210]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Verify the Username expected [] but found [ThiyagarajaN],
verify the password expected [] but found [9876543210]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.cts.test.prog.Facebook_Login_Data.test(Facebook_Login_Data.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="aftermethod" is-config="true" duration-ms="0" started-at="2021-08-12T14:21:50Z" finished-at="2021-08-12T14:21:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="beforemethod" is-config="true" duration-ms="16" started-at="2021-08-12T14:21:50Z" finished-at="2021-08-12T14:21:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="FAIL" signature="test(java.lang.String, java.lang.String)[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="test" duration-ms="1171" started-at="2021-08-12T14:21:50Z" data-provider="login" finished-at="2021-08-12T14:21:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raja]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12345]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Verify the Username expected [] but found [ThiyagarajaN],
verify the password expected [] but found [9876543210]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Verify the Username expected [] but found [ThiyagarajaN],
verify the password expected [] but found [9876543210]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.cts.test.prog.Facebook_Login_Data.test(Facebook_Login_Data.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="FAIL" signature="test(java.lang.String, java.lang.String)[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="test" duration-ms="1103" started-at="2021-08-12T14:21:51Z" data-provider="login" finished-at="2021-08-12T14:21:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Sekar]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[12354]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Verify the Username expected [] but found [ThiyagarajaN],
verify the password expected [] but found [9876543210]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Verify the Username expected [] but found [ThiyagarajaN],
verify the password expected [] but found [9876543210]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.cts.test.prog.Facebook_Login_Data.test(Facebook_Login_Data.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="beforemethod()[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="beforemethod" is-config="true" duration-ms="0" started-at="2021-08-12T14:21:51Z" finished-at="2021-08-12T14:21:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="aftermethod" is-config="true" duration-ms="0" started-at="2021-08-12T14:21:51Z" finished-at="2021-08-12T14:21:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method status="PASS" signature="afterclass()[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="afterclass" is-config="true" duration-ms="1071" started-at="2021-08-12T14:21:53Z" finished-at="2021-08-12T14:21:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterclass -->
        <test-method status="PASS" signature="aftermethod()[pri:0, instance:org.cts.test.prog.Facebook_Login_Data@13a5fe33]" name="aftermethod" is-config="true" duration-ms="0" started-at="2021-08-12T14:21:53Z" finished-at="2021-08-12T14:21:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
      </class> <!-- org.cts.test.prog.Facebook_Login_Data -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
